// harness-engineering-py/frontend/src/components/agents/AgentCard.vue
<template>
  <el-card shadow="hover" class="agent-card">
    <div class="agent-header">
      <div class="agent-icon">
        <el-icon :size="20"><component :is="iconComponent" /></el-icon>
      </div>
      <div class="agent-info">
        <h3 class="agent-name">{{ agent.name }}</h3>
        <p class="agent-desc">{{ agent.description }}</p>
      </div>
    </div>
    <div class="agent-tags">
      <el-tag v-for="tag in agent.tags" :key="tag" size="small" type="info">{{ tag }}</el-tag>
    </div>
  </el-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import * as Icons from '@element-plus/icons-vue'
import type { Agent } from '@/types'

const props = defineProps<{ agent: Agent }>()

const iconComponent = computed(() => {
  const iconMap: Record<string, any> = {
    Bot: Icons.Robot,
    FlaskConical: Icons.Orange,
    Server: Icons.Monitor,
    BookOpen: Icons.Reading,
    ShieldCheck: Icons.Checked,
    BarChart3: Icons.DataAnalysis,
    Blocks: Icons.Grid,
    GitBranch: Icons.Connection,
  }
  return iconMap[props.agent.icon] || Icons.Robot
})
</script>

<style scoped>
.agent-card {
  cursor: pointer;
  transition: transform 0.2s;
}
.agent-card:hover {
  transform: translateY(-2px);
}
.agent-header {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}
.agent-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  border-radius: 8px;
  background: var(--el-color-success-light-9);
  color: var(--el-color-success);
  flex-shrink: 0;
}
.agent-info {
  min-width: 0;
  flex: 1;
}
.agent-name {
  margin: 0 0 4px;
  font-size: 14px;
  font-weight: 600;
}
.agent-desc {
  margin: 0;
  font-size: 13px;
  color: var(--el-text-color-secondary);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.agent-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 12px;
}
</style>

// harness-engineering/src/components/agents/agent-card.tsx
import { cn } from "@/lib/utils"
import type { Agent } from "@/types"
import * as LucideIcons from "lucide-react"

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function DynamicIcon({ name, ...props }: { name: string } & any) {
  const icons = LucideIcons as unknown as Record<string, React.ComponentType<any>>
  const Icon = icons[name]
  if (!Icon) return <LucideIcons.Bot {...props} />
  return <Icon {...props} />
}

export function AgentCard({ agent }: { agent: Agent }) {
  return (
    <div className="rounded-lg border bg-card p-5 hover:shadow-md transition-shadow">
      <div className="flex items-start gap-3">
        <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-primary/10 text-primary shrink-0">
          <DynamicIcon name={agent.icon} className="h-5 w-5" />
        </div>
        <div className="min-w-0 flex-1">
          <h3 className="font-semibold text-sm">{agent.name}</h3>
          <p className="text-sm text-muted-foreground mt-1 line-clamp-2">{agent.description}</p>
        </div>
      </div>
      <div className="flex flex-wrap gap-1.5 mt-3">
        {agent.tags.map((tag) => (
          <span key={tag} className={cn(
            "inline-flex items-center rounded-md px-2 py-0.5 text-xs font-medium",
            "bg-secondary text-secondary-foreground"
          )}>
            {tag}
          </span>
        ))}
      </div>
    </div>
  )
}
