// harness-engineering/src/components/workflow/chat-stream.tsx
"use client"

import { useRef, useEffect } from "react"
import type { ChatMessage as ChatMessageType } from "@/types/chat"
import { ChatMessage } from "./chat-message"

interface ChatStreamProps { messages: ChatMessageType[]; onResolvePermission?: (requestId: string, optionId: string) => void }

export function ChatStream({ messages, onResolvePermission }: ChatStreamProps) {
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }) }, [messages])

  return (
    <div className="flex-1 overflow-y-auto py-4">
      {messages.length === 0 && (
        <div className="flex items-center justify-center h-full text-muted-foreground text-sm">开始对话吧...</div>
      )}
      {messages.map((msg) => <ChatMessage key={msg.id} message={msg} onResolvePermission={onResolvePermission} />)}
      <div ref={bottomRef} />
    </div>
  )
}

// harness-engineering-py/frontend/src/components/workflow/ChatStream.vue
<template>
  <div class="chat-stream" ref="scrollContainer">
    <div v-if="messages.length === 0" class="chat-empty">
      <el-empty description="发送消息开始对话" />
    </div>
    <ChatMessage
      v-for="msg in messages"
      :key="msg.id"
      :message="msg"
      @resolve-permission="(reqId, optId) => $emit('resolvePermission', reqId, optId)"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import type { ChatMessage as ChatMessageType } from '@/types/chat'
import ChatMessage from './ChatMessage.vue'

const props = defineProps<{
  messages: ChatMessageType[]
}>()

defineEmits<{
  resolvePermission: [requestId: string, optionId: string]
}>()

const scrollContainer = ref<HTMLElement>()

function scrollToBottom() {
  nextTick(() => {
    if (scrollContainer.value) {
      scrollContainer.value.scrollTop = scrollContainer.value.scrollHeight
    }
  })
}

watch(() => props.messages.length, scrollToBottom)
watch(() => props.messages, scrollToBottom, { deep: true })
</script>

<style scoped>
.chat-stream {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}
.chat-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
}
</style>
